### PR TITLE
[WIP] Nuxt 2 support

### LINKED ISSUE #9: Nuxt2 support
The module currently only supports Nuxt3 but it definitely can support Nuxt2. Add support for Nuxt2 as well.

### PR DESCRIPTION
**Pull request by steveworkman**
Fixes #9

So far this is a refactor of the render code to split it for nuxt 2 and nuxt 3

### CODE REVIEW

**Comment by steveworkman** [comment]
ToDo:

- [ ] Nuxt 2 tests don't run because the webpack configuration validation fails saying that `/\.js$/i` is not a regular expression 🤯
- [ ] Wrap the Vite plugin in an unplugin to get it wrapping components in Webpack
- [ ] Re-work the Vue2 server rendering wrapper - the one in here right now is not in use

**Comment by steveworkman** [comment]
However, with it in its current state, the nuxt 2 playground runs and builds in SSR mode without crashing and most of the components hydrate correctly. DSD is not added but that will be solved by the above changes

**Comment by steveworkman** [comment]
Today I replaced the `@open-wc/import-meta-loader` with one that resolves local file paths rather than just webpack localhost ones. This is fine in dev, but it doesn't build, saying it can't find the module. If I get that to find the module, it complains that `source.replace is not a function` - seemingly some objects other than strings are being passed through it, and it falls over.

Beyond that, `vue-server-renderer` for nuxt 2 needs the `fs` module that it is trying to load client-side, and beyond that, the latest `nuxt` RC is causing the component that is loaded first to be added as another document fragment, instead of replacing the SSR one, I think due to https://github.com/nuxt/framework/pull/7527 or https://github.com/nuxt/framework/pull/7713.

I'm no longer sure that the current approach of wrapping components will work, and we should look at rendering hooks instead

**Comment by matthewhardern** [comment]
Going off the back of your last commit I have managed to get it to spit out what I think is correct by making the following changes.

LitRenderer.ts

```// Notes on placement of the DOM shim
/* It must be placed above the render-lit-html file or that fails as it needs the shim APIs
 * It must also be placed AFTER the vue-router has initialised. The only way to do that in Nuxt 3 is to have it
 * here, directly before the render-lit-html file.
 * For Nuxt 2, it does not have to be here, but it _must_ be present before the components are loaded,
 * so it is registered as a plugin
 * Having it twice for Nuxt 2 does nothing as the shim is a singleton and will not overwrite itself if it is
 * already installed
 */
import "@lit-labs/ssr/lib/install-global-dom-shim.js";
import "@lit-labs/ssr/lib/render-lit-html.js";
import {html, __unsafeHTML} from "ultrahtml";

import { LitElementRenderer } from "@lit-labs/ssr/lib/lit-element-renderer.js";
import { isCustomElementTag, getCustomElementConstructor } from "./customElements";

// This `any` could a VNode from Vue3 or Vue2
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function renderLitElement(tagName: string, vNode: any): {value: string} {
  if (!vNode || !isCustomElementTag(tagName)) {
    return;
  }
  try {
    const renderer = new LitElementRenderer(tagName);

    attachPropsToRenderer(renderer, tagName, vNode);

    renderer.connectedCallback();

    const shadowContents = __unsafeHTML(getShadowContents(renderer));

    return html`<${tagName}${getAttributesToRender(
      renderer
    )}><template shadowroot="open">${shadowContents}</template>${vNode.children}</${tagName}>`;
  } catch (e) {
    // eslint-disable-next-line no-console
    console.error(e);
    return "";
  }
}

function attachPropsToRenderer(renderer, tagName, vNode) {
  const customElementConstructor = getCustomElementConstructor(tagName);
  const props = vNode.props;
  if (props) {
    for (const [key, value] of Object.entries(props)) {
      // check if this is a reactive property
      if (
        customElementConstructor !== null &&
        typeof customElementConstructor !== "string" &&
        customElementConstructor.elementProperties.get(key)
      ) {
        // This gets around the issue of properties having a key but no value
        if (value === "") {
          renderer.setProperty(key, true);
        } else {
          renderer.setProperty(key, value);
        }
      } else {
        renderer.setAttribute(key, value);
      }
    }
  }
}

function getAttributesToRender(renderer: LitElementRenderer): string {
  if (renderer.element.attributes) {
    return iterableToString(renderer.renderAttributes());
  }
  return "";
}

function getShadowContents(renderer: LitElementRenderer): string {
  return iterableToString(renderer.renderShadow({}));
}

function iterableToString(iterable: Iterable<string>) {
  let s = "";
  for (const i of iterable) {
    s += i;
  }
  return s;
}
```

nitroLitRenderer.ts

```
import type { NitroApp } from "nitropack";
import { NuxtRenderHTMLContext } from "#imports";
import { transform } from "ultrahtml";
import { renderLitElement } from "~/utils/litRenderer";
import swap from "ultrahtml/transformers/swap";

export default defineNitroPlugin((nitroApp: NitroApp) => {
    nitroApp.hooks.hook("render:html", async (htmlContext: NuxtRenderHTMLContext) => {
        await renderAllElements(htmlContext);
    });
});

// This may not be efficient, but it works
async function renderAllElements(htmlContext: NuxtRenderHTMLContext) {
    for (let i = 0; i < htmlContext.body.length; i++) {
        const markup = htmlContext.body[i];

        const customElementList = {};

        for (let key of customElements.__definitions.keys()) {
            customElementList[key] = (props, children) => {
                return renderLitElement(key, { children: children, props: props });
            }
        }

        htmlContext.body[i] = await transform(markup, [
            swap(customElementList)
        ]);
    }
}
```
However I am not 100% certain so if you could let me know that would be great.

**Comment by prashantpalikhe** [comment]
Closing this for now. We can revisit it later if we want to add the Nuxt2 support.

**Comment by 516310460** [comment]
Help nuxt2

**Pull request closed without merging**
